import type { Theme } from "../types";

export const themes: Theme[] = [
  {
    id: "minimal",
    name: "Minimal",
    hljsTheme: "github",
    vars: {
      "--bg-primary": "#ffffff",
      "--bg-secondary": "#f8f8f8",
      "--text-primary": "#222222",
      "--text-secondary": "#666666",
      "--text-heading": "#111111",
      "--accent": "#333333",
      "--border": "#e0e0e0",
      "--code-bg": "#f4f4f4",
      "--blockquote-border": "#cccccc",
      "--link-color": "#0066cc",
      "--font-body": "'Georgia', serif",
      "--font-heading": "'Georgia', serif",
      "--font-code": "'JetBrains Mono', 'Fira Code', monospace",
    },
  },
  {
    id: "obsidian",
    name: "Obsidian",
    hljsTheme: "atom-one-dark",
    vars: {
      "--bg-primary": "#1e1e1e",
      "--bg-secondary": "#252525",
      "--text-primary": "#dcddde",
      "--text-secondary": "#999999",
      "--text-heading": "#ffffff",
      "--accent": "#7c5cbf",
      "--border": "#333333",
      "--code-bg": "#2a2a2a",
      "--blockquote-border": "#7c5cbf",
      "--link-color": "#a78bfa",
      "--font-body": "'Inter', sans-serif",
      "--font-heading": "'Inter', sans-serif",
      "--font-code": "'JetBrains Mono', 'Fira Code', monospace",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    hljsTheme: "atom-one-dark",
    vars: {
      "--bg-primary": "#282a36",
      "--bg-secondary": "#21222c",
      "--text-primary": "#f8f8f2",
      "--text-secondary": "#6272a4",
      "--text-heading": "#ff79c6",
      "--accent": "#bd93f9",
      "--border": "#44475a",
      "--code-bg": "#21222c",
      "--blockquote-border": "#ff79c6",
      "--link-color": "#8be9fd",
      "--font-body": "'Inter', sans-serif",
      "--font-heading": "'Inter', sans-serif",
      "--font-code": "'JetBrains Mono', 'Fira Code', monospace",
    },
  },
  {
    id: "nord",
    name: "Nord",
    hljsTheme: "atom-one-dark",
    vars: {
      "--bg-primary": "#2e3440",
      "--bg-secondary": "#3b4252",
      "--text-primary": "#d8dee9",
      "--text-secondary": "#81a1c1",
      "--text-heading": "#eceff4",
      "--accent": "#88c0d0",
      "--border": "#434c5e",
      "--code-bg": "#3b4252",
      "--blockquote-border": "#88c0d0",
      "--link-color": "#81a1c1",
      "--font-body": "'Inter', sans-serif",
      "--font-heading": "'Inter', sans-serif",
      "--font-code": "'JetBrains Mono', 'Fira Code', monospace",
    },
  },
  {
    id: "solarized",
    name: "Solarized Dark",
    hljsTheme: "solarized-dark",
    vars: {
      "--bg-primary": "#002b36",
      "--bg-secondary": "#073642",
      "--text-primary": "#839496",
      "--text-secondary": "#657b83",
      "--text-heading": "#fdf6e3",
      "--accent": "#b58900",
      "--border": "#073642",
      "--code-bg": "#073642",
      "--blockquote-border": "#b58900",
      "--link-color": "#268bd2",
      "--font-body": "'Inter', sans-serif",
      "--font-heading": "'Inter', sans-serif",
      "--font-code": "'JetBrains Mono', 'Fira Code', monospace",
    },
  },
  {
    id: "tokyonight",
    name: "Tokyo Night",
    hljsTheme: "atom-one-dark",
    vars: {
      "--bg-primary": "#1a1b2e",
      "--bg-secondary": "#16213e",
      "--text-primary": "#a9b1d6",
      "--text-secondary": "#565f89",
      "--text-heading": "#c0caf5",
      "--accent": "#7aa2f7",
      "--border": "#292e42",
      "--code-bg": "#16213e",
      "--blockquote-border": "#7aa2f7",
      "--link-color": "#7dcfff",
      "--font-body": "'Inter', sans-serif",
      "--font-heading": "'Inter', sans-serif",
      "--font-code": "'JetBrains Mono', 'Fira Code', monospace",
    },
  },
  {
    id: "catppuccin",
    name: "Catppuccin Mocha",
    hljsTheme: "atom-one-dark",
    vars: {
      "--bg-primary": "#1e1e2e",
      "--bg-secondary": "#181825",
      "--text-primary": "#cdd6f4",
      "--text-secondary": "#9399b2",
      "--text-heading": "#cba6f7",
      "--accent": "#89dceb",
      "--border": "#313244",
      "--code-bg": "#181825",
      "--blockquote-border": "#cba6f7",
      "--link-color": "#89b4fa",
      "--font-body": "'Inter', sans-serif",
      "--font-heading": "'Inter', sans-serif",
      "--font-code": "'JetBrains Mono', 'Fira Code', monospace",
    },
  },
  {
    id: "things",
    name: "Things",
    hljsTheme: "github",
    vars: {
      "--bg-primary": "#faf9f7",
      "--bg-secondary": "#f2ede8",
      "--text-primary": "#3d2b1f",
      "--text-secondary": "#8c7b6e",
      "--text-heading": "#2a1a0e",
      "--accent": "#c0533a",
      "--border": "#e0d6ce",
      "--code-bg": "#ede8e3",
      "--blockquote-border": "#c0533a",
      "--link-color": "#b04a28",
      "--font-body": "'Georgia', serif",
      "--font-heading": "'Georgia', serif",
      "--font-code": "'JetBrains Mono', 'Fira Code', monospace",
    },
  },
  {
    id: "gruvbox",
    name: "Gruvbox",
    hljsTheme: "atom-one-dark",
    vars: {
      "--bg-primary": "#282828",
      "--bg-secondary": "#1d2021",
      "--text-primary": "#ebdbb2",
      "--text-secondary": "#a89984",
      "--text-heading": "#fabd2f",
      "--accent": "#fe8019",
      "--border": "#3c3836",
      "--code-bg": "#1d2021",
      "--blockquote-border": "#fe8019",
      "--link-color": "#83a598",
      "--font-body": "'Inter', sans-serif",
      "--font-heading": "'Inter', sans-serif",
      "--font-code": "'JetBrains Mono', 'Fira Code', monospace",
    },
  },
  {
    id: "everforest",
    name: "Everforest",
    hljsTheme: "atom-one-dark",
    vars: {
      "--bg-primary": "#2d353b",
      "--bg-secondary": "#272e33",
      "--text-primary": "#d3c6aa",
      "--text-secondary": "#9da9a0",
      "--text-heading": "#e9e8d2",
      "--accent": "#a7c080",
      "--border": "#3d484d",
      "--code-bg": "#272e33",
      "--blockquote-border": "#a7c080",
      "--link-color": "#7fbbb3",
      "--font-body": "'Inter', sans-serif",
      "--font-heading": "'Inter', sans-serif",
      "--font-code": "'JetBrains Mono', 'Fira Code', monospace",
    },
  },
];

export const DEFAULT_THEME_ID = "obsidian";
